### ISSUE TITLE
MonoTel compatible ?

### ISSUE THREAD

**Issue by Nick75wien** [andyboeh/esphome-elero#6]
Hello!

I found your project and it might be a solution to control my Schlotterer window rollos. 
I have a MonoTel remote control by elero and so I wonder if your solution is compatible with that?

KR Niki

**Comment by andyboeh** [comment]
Short answer: It depends. 
Long answer: There are two Elero protocols supported by your MonoTel. Only the bidirectional one works. Please check the manual: file:///home/andy/Downloads/MonoTel%202%20-%20Operating%20instruction%20-%20Radio%20hand-held%20transmitters.pdf

**Comment by Nick75wien** [comment]
Thanks, but I can‘t see the pdf

**Comment by andyboeh** [comment]
Sorry, I accidentally copied the wrong link - fixed.

**Comment by Nick75wien** [comment]
Thanks! My remote looks really old in contrast to that:
![IMG_4389](https://github.com/user-attachments/assets/673eb3ca-c672-45b0-9b25-c07f10d07501)
![IMG_4390](https://github.com/user-attachments/assets/4812d97a-6700-4dde-81d0-06411e0425d9)

**Comment by andyboeh** [comment]
Uh... I don't know what protocol those speak, probably the old, unsupported one. If the blinds are older than ca. 10 years, it's the old protocol.

**Comment by Nick75wien** [comment]
now that I have the hardware and some time to play arround I wonder if I need to install anything elese on Home Assistant or just flash the ESP32 with your code ?

**Comment by andyboeh** [comment]
Just flash it with ESPHome and the custom component. Home Assistant will automatically pick up the covers once you add the ESPHome device.
