### ISSUE TITLE
Elero uni-directional protocol support

### ISSUE THREAD

**Issue by ggggh** [andyboeh/esphome-elero#8]
I use a Tempotel2, but my elero 868 modules are the unidirectional ones.  I haven't found a statement saying they are not supported, but from reading another of the reported issues here using a Monotel, I infer that non-bidirectional devices won't work?  Is that correct?

**Comment by andyboeh** [comment]
The README states that only the bidirectional protocol is supported. I agree, though, that this is just in one sentence and not completely obvious. So no: unidirectonal ones are unsupported. I spent many hours on trying to get the unidirectional ones in (I have a few unidirectional blinds as well), but I'm just going to replace the motors.
